// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfzdtgulalwvmmfuoaft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmemR0Z3VsYWx3dm1tZnVvYWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjE1NDksImV4cCI6MjA3MzQ5NzU0OX0.dVv8rgA16JeyjmlqJ-gBcCOE0WN8_UyTSZKkYxdXPn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});